services:
  mongo:
    image: mongo
    container_name: "mongo-db"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    networks:
      - processor
    ports:
      - "27017:27017"

  processor:
    image: ghcr.io/qubic/frontend-processor:dev
    container_name: frontend_processor
    networks:
      - processor
    depends_on:
      - mongo
    restart: unless-stopped

networks:
  processor: